# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

pod 'FireStore'
pod 'Firebase/Core', '~> 5.12.0'
pod 'Firebase/Firestore', '~> 5.12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end